# Generated by Django 3.1.5 on 2021-09-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial_20210729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsBot',
        ),
    ]
