# Generated by Django 4.2.3 on 2025-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("slackbot", "0003_auto_20210915_1137")]

    operations = [
        migrations.CreateModel(
            name="SlackMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=128)),
                ("ts", models.CharField(max_length=32)),
                ("channel_id", models.CharField(max_length=32)),
                ("client_msg_id", models.CharField(max_length=64)),
                ("reactions", models.JSONField(blank=True)),
                ("reply_count", models.IntegerField(blank=True)),
                ("reply_users", models.JSONField(blank=True, default=list)),
                ("reply_users_count", models.IntegerField(blank=True)),
                ("team", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("thread_timestamp", models.DateTimeField(blank=True, null=True)),
                ("time_stamp", models.DateTimeField()),
                ("type", models.CharField(max_length=32)),
                ("user", models.CharField(max_length=32)),
                ("message_from", models.CharField(max_length=128)),
                ("user_team", models.CharField(max_length=32)),
                ("thread_message", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Slack Message",
                "verbose_name_plural": "Slack Messages",
            },
        ),
        migrations.AddConstraint(
            model_name="slackmessage",
            constraint=models.UniqueConstraint(
                fields=("ts", "channel"), name="unique_ts_channel"
            ),
        ),
    ]
